osx_image: xcode61
language: objective-c

before_install:
  - brew update
  - brew install xctool

script: xctool -workspace CMPopTipView.xcworkspace -scheme CMPopTipViewTests -sdk iphonesimulator build test
